### ISSUE TITLE
pages link not to the top

### ISSUE THREAD

**Issue by nicferrier** [nicferrier/gnudoc-js#10]
Not sure why this happens. 

Sometimes when you visit a link the content loads with the view set half way down or something.

I don't understand the conditions this happens under.

**Comment by mediremi** [comment]
I think that it's because of the hash in the url. The browser looks for it before the content loads.

**Comment by nicferrier** [comment]
Well, yes. I thought the fragment was at the top of the content. But it isn't. So I guess the fragment needs to be set as an id on one of the DOM nodes at the top of the content.

Something like:

```
$("div.node", $("#body",$("#viewer")[0]))[0]
```
