### ISSUE TITLE
bottom of the page has spurious whitespace in chrome

### ISSUE THREAD

**Issue by nicferrier** [nicferrier/gnudoc-js#7]
![screenshot from 2014-08-13 03 14 14](https://cloud.githubusercontent.com/assets/245513/3900525/a8acdd58-228f-11e4-90c4-306065fd9b9d.png)

Above is an example.

This seems to happen when you squash the column space up so the columns truncate. 

Not sure if that is the problem or if it's unrelated.

**Comment by mediremi** [comment]
[My pull request](https://github.com/nicferrier/gnudoc-js/pull/1) caused this.

The solution is

``` css
footer {
  overflow: hidden;
}
```

[PR that fixes this](https://github.com/nicferrier/gnudoc-js/pull/9)
